### ISSUE TITLE
LoaderExceptionModCrash (generic crash log)

### ISSUE THREAD

**Issue by piedpipr314** [phantamanta44/libnine#3] opened 2019-07-17 19:17 UTC
Pastebin: https://pastebin.com/ZmS5LiY5

I'll see if I can figure this one out, might be a mod conflict I'm thinking.

**Comment by phantamanta44** [comment] 2019-07-17 19:18
dupe of #2 - update to libnine 1.1.0 and it should be fixed

**Closed as completed** 2019-07-17 19:19 UTC
